var  read_me = "developed by muffinmix :3"

    /* =====================================
                    place file in [Scipt UI Panels] folder
                                typically found at :
    C:\Program Files\Adobe\Adobe After Effects 20XX\Support Files\Scripts\ScriptUI Panels 
    ========================================= */

    /* ============================
    -quick explanation of button functionality
    ============================== 
ADJ: button click creates a trimmed adjustment layer for each layer you have selected
         alt-click will create 1 long adjustment layer whose duration spans from the first to last layer selected
        if no layer is selected, creates adj spanning the full comp duration

NULL: on-click creates a trimmed null autoparented to the first layer selected
            if no layer is selected, creates null spanning the full comp duration

TEXT: on-click creates a trimmed text layer for each layer you have selected. 
            if no layer is selected, creates text spanning the full comp duration
            *has advantage of anchor point being centered compared to default ae
            
SOLID: button click creates a black solid trimmed to first selected layer
        alt-clicking the button will let you select the solid color beforehand
        if no layer is selected, creates solid spanning the full comp duration

ƒ: button click creates "one framers" at the location of your Current Time Indicator (CTI) / playhead
    *the amount is based on the number selected from the drop down menu
    
rst: resets position, scale, opacity, roation, anchor point, and audio level if applicable
*/

eval("@JSXBIN@ES@2.0@MyBbyBn0AFJAnASzEjDjPjOjWByBARFFdyBFdAFdBFdCFdDfnftJBnASzCjYhRCyB\
ndDftJCnASzIjBjEjKiDjPjVjOjUDyBndBftODbyEn0ABJEnASzHjSjFjBjEifjNjFEyBneAftACzCh\
dhdFVEfyBnnbnJ2gfCnAENyBnAMGbyBnACMIbyBnALMlUbyBn0ATOlVbylWn0ABJlWnASzKjTjUjBjS\
jUiWjBjMjVjFGIARDFdBFdBFdBfnffAUzCjcjcHhzBhBIVGfICzChBhdJXzGjMjFjOjHjUjIKfVGfIn\
ndDnnnJlZnASzEjDjPjNjQLAXzKjBjDjUjJjWjFiJjUjFjNMfXzHjQjSjPjKjFjDjUNfjzDjBjQjQOf\
nftOlablbn0ACJlbnAEjzFjBjMjFjSjUPfRBFeTiOjPhAjDjPjNjQhAjJjThAjTjFjMjFjDjUjFjEff\
ZlcnAAREFdAFdAFdAFdBfAUHhIVLfAhICzKjJjOjTjUjBjOjDjFjPjGQVLfAjzIiDjPjNjQiJjUjFjN\
RfnnnnnJmAnASzHjOjFjXiOjVjMjMSBEXzHjBjEjEiOjVjMjMTfXzGjMjBjZjFjSjTUfVLfAnfnftJm\
BnASzPjOjFjXiDjPjMjPjSiDjPjOjUjSjPjMVCEXzLjBjEjEiQjSjPjQjFjSjUjZWfEXzIjQjSjPjQj\
FjSjUjZXfVSfBRBFeSiBiEiCiFhAiFjGjGjFjDjUhAiQjBjSjBjEjFffRBFeSiBiEiCiFhAiDjPjMjP\
jShAiDjPjOjUjSjPjMffnftJmCnASzMjUjIjFiDjPjMjPjSiQjSjPjQYDEXXfVVfCRBFeXiBiEiCiFh\
AiDjPjMjPjShAiDjPjOjUjSjPjMhNhQhQhQhRffnftJmFnASzQjPjSjJjHiTjIjZiDjPjOjEjJjUjJj\
PjOZEXzNjIjJjEjFiTjIjZiMjBjZjFjSjTgafVLfAnftOmGJmGnABXgafVLfAnctfACFVZfEnncfnJm\
HnABXzDjTjIjZgbfVSfBnctfJmInABXzHjFjOjBjCjMjFjEgcfVSfBncffJmLnAEXzIjTjFjUiWjBjM\
jVjFgdfVYfDRBVGfIffJmOnASzLjFjEjJjUiWjBjMjVjFiJiEgeFEXzRjGjJjOjEiNjFjOjViDjPjNj\
NjBjOjEiJjEgffjOfRBFeNiFjEjJjUhAiWjBjMjVjFhOhOhOffnftJmPnABXzIjTjFjMjFjDjUjFjEh\
AfVYfDnctfJmQnAEXzOjFjYjFjDjVjUjFiDjPjNjNjBjOjEhBfjOfRBVgefFffJmTnASzGjSjFjTjVj\
MjUhCGXzFjWjBjMjVjFhDfVYfDnftOmWbymXn0ABJmXnAEXzGjSjFjNjPjWjFhEfVSfBnfAVSfBnJmb\
nABXgafVLfAVZfEnfJmenASzQjTjUjBjSjUiWjBjMjVjFiJjOiSjHjCjBhFHAREXzBhQhGfVGfIXzBh\
RhHfVGfIXzBhShIfVGfIFdBfnftZmfnAdCFEXzIjUjPiTjUjSjJjOjHhJfVhCfGnfEXhJfVhFfHnfnn\
FbVhCfGAJV4C0AiAY4D0AiAZ4E0AiAge4F0AiAhF4H0AiAG40BhAL40BiAS4B0AiAhC4G0AiABIAzXi\
HjPjPjEiCjPjZiOjJjOjKjBiDjPjMjPjSiQjJjDjLjFjShKAnAMnDbyBn0ADJnEnASzDjOjVjNhLAXh\
GfVzFjBjSjSjBjZhMfCnftOnFbynHn0ABanHbynIn0ABOnIbynJn0ABJnJnAShLAQzAhNfVhMfCVzBj\
JhOfBnffACzBhchPQhNfVhMfCVhOfBVhLfAnnnAVhOfBBXKfVhMfCByBhPAVzBjChQfDbynPn0ABanP\
bynQn0ABOnQbynRn0ABJnRnAShLAQhNfVhMfCVhOfBnffACzBhehRQhNfVhMfCVhOfBVhLfAnnnAVhO\
fBBXKfVhMfCByBhPZnVnAVhLf0AEhO4B0AiAhL40BiAhQ4B0AhAhM40BhACCAzGjNjJjOjNjBjYhSAn\
WMnYbyBn0AGJnanAEXzOjCjFjHjJjOiVjOjEjPiHjSjPjVjQhTfjOfRBFeUiOjFjXhAiBjEjKjVjTjU\
jNjFjOjUhAiMjBjZjFjSffJnbnASLAXMfXNfjOfnftJncnASzRjTjFjMjFjDjUjFjEiMjBjZjFjSjTi\
BjSjShUBXzOjTjFjMjFjDjUjFjEiMjBjZjFjSjThVfVLfAnftJndnASzLjOjVjNiTjFjMjFjDjUjFjE\
hWCXKfXhVfVLfAnftOnfb2BBn0AFJ2BBnASzFjJjOiQjUjThXDEjzFiBjSjSjBjZhYfntnftJ2CBnAS\
zGjPjVjUiQjUjThZEEjhYfntnftJ2DBnASzDjJjOjEhaFEjhYfntnfta2GBb2HBn0ADJ2HBnAEXzEjQ\
jVjTjIhbfVhXfDRBXzHjJjOiQjPjJjOjUhcfQhNfVhUfBVzBjKhdfGffJ2IBnAEXhbfVhZfERBXzIjP\
jVjUiQjPjJjOjUhefQhNfVhUfBVhdfGffJ2JBnAEXhbfVhafFRBXzFjJjOjEjFjYhffQhNfVhUfBVhd\
fGffAVhdfGAVhWfCByBhPO2NBb2PBn0AMJ2PBnASzDiNiJiOiAHEjhSfRCVhXfDFdBffnftJ2QBnASz\
DiNiBiYiBIEjhSfRCVhZfEFdAffnftJ2RBnASzFjNjJjOjJjOiCJEjhSfRCVhafFFdBffnftJ2SBnAS\
zMjGjJjSjTjUiJjOiQjPjJjOjUiDKViAfHnftJ2TBnASzMjMjBjTjUiPjVjUiQjPjJjOjUiELViBfIn\
ftJ2WBnASzBjTiFMXzEjOjBjNjFiGfXhGfVhUfBnftO2XBby2YBn0ABJ2YBnASiFMEXzJjTjVjCjTjU\
jSjJjOjHiHfXiGfXhGfVhUfBRCFdJFdRffnffACFEXiHfViFfMRCFdAFdHffnneHjBjEjKhAjGjPjSb\
y2gbBn0ABJ2gbBnASiFMEXiHfXiGfXhGfVhUfBRCFdAFdIffnffJ2gfBnASzIjBjEjKiMjBjZjFjSiI\
NEXzIjBjEjEiTjPjMjJjEiJfXUfVLfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8ka\
kZkZkZkZkZmJhffCzBhLiKnViFfMeIjBjEjKhAjGjPjShAnXzFjXjJjEjUjIiLfVLfAXzGjIjFjJjHj\
IjUiMfVLfAFdBFdBffnftJ2hABnABXzPjBjEjKjVjTjUjNjFjOjUiMjBjZjFjSiNfViIfNnctfJ2hBB\
nABXhcfViIfNViAfHnfJ2hCBnABXhefViIfNViBfInfJ2hDBnAEXzKjNjPjWjFiCjFjGjPjSjFiOfVi\
IfNRBQhNfVhUfBViCfJffAXzGjBjMjUiLjFjZiPfXzNjLjFjZjCjPjBjSjEiTjUjBjUjFiQfXzLjFjO\
jWjJjSjPjOjNjFjOjUiRfjzIiTjDjSjJjQjUiViJiSfby2hHBn0ABa2hHBb2hIBn0AGJ2hIBnASiFMX\
iGfQhNfVhUfBVhOfOnftO2hKBby2hLBn0ABJ2hLBnASiFMEXiHfXiGfQhNfVhUfBVhOfORCFdIFdRff\
nffACFEXiHfViFfMRCFdAFdHffnneHjBjEjKhAjGjPjSby2hOBn0ABJ2hOBnASiFMEXiHfXiGfQhNfV\
hUfBVhOfORCFdAFdIffnffJ2hQBnASzIjOjFjXiTjPjMjJjEiTPEXiJfXUfVLfARGARDFd8kakZkZkZ\
kZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffCiKnViFfMeIjBjEjKhAjGjPjShAnXiLf\
VLfAXiMfVLfAFdBCzBhNiUQhNfVhZfEVhOfOQhNfVhXfDVhOfOnnffnftJ2hRBnABXiNfViTfPnctfJ\
2hSBnABXhcfViTfPQhNfVhXfDVhOfOnfJ2hTBnAEXiOfViTfPRBQhNfVhUfBVhOfOffAVhOfOAVhWfC\
ByBhPAChRVhWfCnndAb2hbBn0ADJ2hbBnASiTPEXiJfXUfVLfARGARDFd8kakZkZkZkZkZmJhfFd8ka\
kZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeGjBjEjKhAhahTXiLfVLfAXiMfVLfAFdBXzQjXjPjSjL\
iBjSjFjBiEjVjSjBjUjJjPjOiVfVLfAffnftJ2hcBnABXiNfViTfPnctfJ2hdBnABXhcfViTfPXzNjX\
jPjSjLiBjSjFjBiTjUjBjSjUiWfVLfAnfJ2hfBnAEXzMjFjOjEiVjOjEjPiHjSjPjVjQiXfjOfnfARh\
O4O0AiAhd4G0AiAiF4M0AiAhU4B0AiAhW4C0AiAhX4D0AiAhZ4E0AiAha4F0AiAiA4H0AiAiB4I0AiA\
iC4J0AiAiD4K0AiAiE4L0AiAiI4N0AiAL40BiAD40BhAiT4P0AiABQAzJjDjSjFjBjUjFiBjEjKiYA2\
iABM2iCBbyBn0AFJ2iDBnAEXhTfjOfRBFeOiOjFjXhAiOjVjMjMhAiMjBjZjFjSffJ2iFBnASLAXMfX\
NfjOfnftJ2iGBnASzNjTjFjMjFjDjUjFjEiMjBjZjFjSiZBXhGfXhVfVLfAnftO2iHBb2iIBn0AEJ2i\
IBnASSCEXTfXUfVLfARBCiUXhefViZfBXhcfViZfBnnffnftJ2iJBnAEXiOfVSfCRBViZfBffJ2iKBn\
ABXhcfVSfCXhcfViZfBnfJ2iLBnABXzGjQjBjSjFjOjUiafViZfBVSfCnfAViZfBb2iPBn0ACJ2iPBn\
ASSCEXTfXUfVLfARBXiVfVLfAffnftJ2iQBnABXhcfVSfCXiWfVLfAnfJ2iSBnAEXiXfjOfnfADiZ4B\
0AiAL40BiAS4C0AiAADAzKjDjSjFjBjUjFiOjVjMjMibA2iTBM2iVBbyBn0ALJ2iYBnASLAXMfXNfjO\
fnftJ2iZBnAShUBXhVfVLfAnftJ2iaBnAShWCXKfXhVfVLfAnftJ2ibBnASzFjDjPjMjPjSicDAREFd\
AFdAFdAFdBfnftO2idBby2ieBn0ABJ2ieBnASicDEjhKfRBARDFdBFdBFdBfffnffAXiPfXiQfXiRfj\
iSfnJ2jABnASzCjUhRidEEXzFjSjPjVjOjEiefjzEiNjBjUjIiffRBCzBhKjAXhGfVicfDnndnfffnf\
tJ2jBBnASzCjUhSjBFEXiefjiffRBCjAXhHfVicfDnndnfffnftJ2jCBnASzCjUhTjCGEXiefjiffRB\
CjAXhIfVicfDnndnfffnftJ2jDBnASzEjUjFjYjUjDHCiKCiKCiKCiKCiKCiKnVidfEeBibnnneBhMV\
jBfFnnnneBhMVjCfGnnnneBidnftJ2jEBnASzDjPjVjUjEIdCJEXhJfVicfDnfnneHhQhMhQhMhQhMh\
RCiKnVjDfHeGiTjPjMjJjEhAnFeLiTjPjMjJjEhAiMjBjZjFjSnftO2jGBb2jHBn0AEJ2jHBnASiZJX\
hGfVhUfBnftJ2jIBnASzJjOjFjXiTjPjMjJjEhSjFKEXiJfXUfVLfARGEXzFjTjMjJjDjFjGfVicfDR\
CFdAFdDffVjEfIXiLfVLfAXiMfVLfAFdBCiUXhefViZfJXhcfViZfJnnffnftJ2jJBnAEXiOfVjFfKR\
BViZfJffJ2jKBnABXhcfVjFfKXhcfViZfJnfAChRVhWfCnndAb2jOBn0ACJ2jOBnASjFKEXiJfXUfVL\
fARGEXjGfVicfDRCFdAFdDffVjEfIXiLfVLfAXiMfVLfAFdBXiVfVLfAffnftJ2jPBnABXhcfVjFfKX\
iWfVLfAnfALiZ4J0AiAid4E0AiAjB4F0AiAjC4G0AiAjF4K0AiAjE4I0AiAhU4B0AiAic4D0AiAhW4C\
0AiAjD4H0AiAL40BiAALAzLjDjSjFjBjUjFiTjPjMjJjEjHA2jTBM2jVBbyBn0AEJ2jWBnAEXhTfjOf\
RBFeOiOjFjXhAiUjFjYjUhAiMjBjZjFjSffJ2jXBnASLAXMfXNfjOfnftO2jYBb2jaBn0AFJ2jaBnAS\
iZBXhGfXhVfVLfAnftJ2jbBnASzHjOjFjXiUjFjYjUjICEXzHjBjEjEiUjFjYjUjJfXUfVLfAnfnftJ\
2jcBnABXhcfVjIfCXhcfViZfBnfJ2jdBnABXhefVjIfCXhefViZfBnfJ2jfBnAEXiOfVjIfCRBViZfB\
ffAChRXKfXhVfVLfAnndAb2kEBn0ACJ2kEBnASjICEXjJfXUfVLfAnfnftJ2kFBnABXhcfVjIfCXiWf\
VLfAnfJ2kIBnAEXiXfjOfnfADiZ4B0AiAjI4C0AiAL40BiAADAzKjDjSjFjBjUjFiUjFjYjUjKA2kJB\
M2kLBbyBn0AGJ2kMBnAEXhTfjOfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJ2kOBnASLAXMfXN\
fjOfnftJ2kPBnASiZBXhGfXhVfVLfAnftJ2kQBnASzDjGjQjTjLCXzJjGjSjBjNjFiSjBjUjFjMfVLf\
AnftK2kSBb2kTBn0AEJ2kTBnASiTEEXiJfXUfVLfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZk\
ZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiLfVLfAXiMfVLfAFdB\
CzBhPjNnXjMfVLfAdBnffnftJ2kUBnABXiNfViTfEnctfJ2kVBnAEXiOfViTfERBViZfBffJ2kXBnAB\
XhcfViTfECiKXhcfViZfBCjAVhOfDXzNjGjSjBjNjFiEjVjSjBjUjJjPjOjOfVLfAnnnnnfAShODVzB\
jYjPfFnftChRVhOfDnndyBThODyBtJ2kZBnAEXiXfjOfnfAGhO4D0AiAiZ4B0AiAjP40BhAjL4C0AiA\
L40BiAiT4E0AiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiMjQA2kaBM2kcBbyBn0AGJ2kdBnAEX\
hTfjOfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJ2kfBnASLAXMfXNfjOfnftJ2lABnASiZBXhG\
fXhVfVLfAnftJ2lBBnASjLCXjMfVLfAnfta2lDBb2lEBn0AEJ2lEBnASiTEEXiJfXUfVLfARGARDFd8\
kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiBjEjKjVjTjUjNjFjOjUh\
AiMjBjZjFjSXiLfVLfAXiMfVLfAFdBCjNnXjMfVLfAdBnffnftJ2lFBnABXiNfViTfEnctfJ2lGBnAE\
XiOfViTfERBViZfBffJ2lIBnABXhcfViTfECiUXhefViZfBCjAVhOfDXjOfVLfAnnnnnfAVhOfDBVjP\
fFByBhPJ2lKBnAEXiXfjOfnfAGhO4D0AiAiZ4B0AiAjP40BhAjL4C0AiAL40BiAiT4E0AiABFAzQjDj\
SjFjBjUjFiPjOjFiGjSjBjNjFjSiSjRA2lLBM2lNBbyBn0AFJ2lPBnASLAXMfXNfjOfnftJ2lQBnASi\
ZBXhGfXhVfVLfAnftJ2lTBnASzFjDjPjVjOjUjSDQhNfjBfjCfnftK2lVBb2lYBn0AHJ2lYBnASiTCE\
XiJfXUfVLfARGARDFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhfFd8kakZkZkZkZkZmJhffFeQiB\
jEjKjVjTjUjNjFjOjUhAiMjBjZjFjSXiLfVLfAXiMfVLfAFdBCjAXjOfVLfAnnd8kFnLiRlYgekFnPh\
fffnffJ2lZBnABXiNfViTfCnctfJ2laBnAEXiOfViTfCRBViZfBffJ2lcBnABXhAfViTfCncffJ2ldB\
nABjzBjZjTfCiKXzEjUjJjNjFjUfVLfACjAVjSfDXjOfVLfAnnnnnfJ2lfBnABXhcfViTfCjjTfnfJ2\
mCBnASjSDCiUnnndBntfAShOEVjPfFnftChRVhOfEnndyBThOEyBtJ2mGBnABXhVfVLfAAnnfAGhO4E\
0AiAiZ4B0AiAjP40BhAjS4D0AiAL40BiAiT4C0AiABFAzQjDjSjFjBjUjFiPjOjFiGjSjBjNjFjSiNj\
VA2mHBM2mKBbyBn0AKJ2mLBnAEXhTfjOfRBFeViDjSjFjBjUjFhAiNjBjTjLhAjGjSjPjNhAiUjFjYj\
UffJ2mMBnASLAXMfXNfjOfnftJ2mNBnASzOjDjSjFjBjUjFiTjIjBjQjFjTiJiEjWBEXgffjOfRBFeX\
iDjSjFjBjUjFhAiTjIjBjQjFjThAjGjSjPjNhAiUjFjYjUffnftJ2mOBnAEXzMjPjQjFjOiJjOiWjJj\
FjXjFjSjXfVLfAnfJ2mPBnASzJjUjFjYjUiMjBjZjFjSjYCXhGfXhVfVLfAnftJ2mQBnASzKjHjMjPj\
CjBjMiUjFjYjUjZDEXhJfXhDfEXXfVjYfCRBFeLiTjPjVjSjDjFhAiUjFjYjUffnfnftJ2mSBnAEXhB\
fjOfRBVjWfBffJ2mUBnASzKjTjIjBjQjFiMjBjZjFjSjaEXhGfXhVfVLfAnfta2mVBb2mWBn0AEa2mW\
Bby2mXBn0ABO2mXBby2mYBn0ABJ2mYBnABXgcfEXXfEXXfVjafERBFeIiDjPjOjUjFjOjUjTffRBQhN\
fVjZfDVhdfGffncffACJVhdfGVhOfFnnby2mcBn0ABJ2mcBnABXgcfEXXfEXXfVjafERBFeIiDjPjOj\
UjFjOjUjTffRBQhNfVjZfDVhdfGffnctfAVhdfGAXKfVjZfDByBhPJ2nABnASzDjEjVjQjbHEXzJjEj\
VjQjMjJjDjBjUjFjcfVjafEnfnftJ2nBBnABXiGfVjbfHQhNfVjZfDVhOfFnfJ2nCBnAEXiOfVjbfHR\
BXhGfXhVfVLfAffAVhOfFAXKfVjZfDByBhPJ2nEBnAEXiXfjOfnfAIhO4F0AiAhd4G0AiAjW4B0AiAj\
Y4C0AiAjZ4D0AiAja4E0AiAjb4H0AiAL40BiAAIAzOjDjSjFjBjUjFiUjFjYjUiNjBjTjLjdA2nFBM2\
nHBbyBn0AJJ2nJBnASLAXMfXNfjOfnftJ2nKBnASjWBEXgffjOfRBFeWiDjSjFjBjUjFhAiNjBjTjLj\
ThAjGjSjPjNhAiUjFjYjUffnftJ2nLBnAEXjXfVLfAnfJ2nMBnASjYCXhGfXhVfVLfAnftJ2nNBnASj\
ZDEXhJfXhDfEXXfVjYfCRBFeLiTjPjVjSjDjFhAiUjFjYjUffnfnftJ2nOBnAEXhBfjOfRBVjWfBffJ\
2nQBnASjaEXhGfXhVfVLfAnfta2nRBb2nSBn0AEa2nSBby2nTBn0ABO2nTBby2nUBn0ABJ2nUBnABXg\
cfEXXfEXXfVjafERBFeIiDjPjOjUjFjOjUjTffRBQhNfVjZfDVhdfGffncffACJVhdfGVhOfFnnby2n\
XBn0ABJ2nXBnABXgcfEXXfEXXfVjafERBFeIiDjPjOjUjFjOjUjTffRBQhNfVjZfDVhdfGffnctfAVh\
dfGAXKfVjZfDByBhPJ2naBnASjbHEXjcfVjafEnfnftJ2nbBnABXiGfVjbfHQhNfVjZfDVhOfFnfJ2n\
cBnAEXiOfVjbfHRBXhGfXhVfVLfAffAVhOfFAXKfVjZfDByBhPJ2nfBnAEXhEfXhGfXhVfVLfAnfAIh\
O4F0AiAhd4G0AiAjW4B0AiAjY4C0AiAjZ4D0AiAja4E0AiAjb4H0AiAL40BiAAIAzPjDjSjFjBjUjFi\
UjFjYjUiNjBjTjLhSjeA2BCNJKnASzHjNjZiQjBjOjFjMjfAdCQVzHjUjIjJjTiPjCjKkAfRjzFiQjB\
jOjFjMkBfnnVkAfREjzGiXjJjOjEjPjXkCfREFeHjQjBjMjFjUjUjFFeNjNjVjGjGjJjOhAjMjBjZjF\
jSjTjzJjVjOjEjFjGjJjOjFjEkDfWzGiPjCjKjFjDjUkEBzKjSjFjTjJjajFjBjCjMjFkFFctftnftJ\
RnABXzNjBjMjJjHjOiDjIjJjMjEjSjFjOkGfVjffAARCFeEjMjFjGjUFeDjUjPjQfnfJSnABXzHjNjB\
jSjHjJjOjTkHfVjffAndFfJTnABXzHjTjQjBjDjJjOjHkIfVjffAndEfJUnABXkGfVjffAARCFeEjGj\
JjMjMFeEjGjJjMjMfnfJVnABXzLjPjSjJjFjOjUjBjUjJjPjOkJfVjffAneFjTjUjBjDjLfJganASzI\
jHjSjPjVjQiPjOjFkKBEXzDjBjEjEkLfVjffARDFeFjHjSjPjVjQjkDfFeIjHjSjPjVjQiPjOjFffnf\
tJgbnABXkGfVkKfBARCFeEjGjJjMjMFeEjGjJjMjMfnfJgdnABXkHfVkKfBndAfJgenABXkIfVkKfBn\
dDfOgfbhAn0AhDJhAnASzDjBjEjKkMCEXkLfVkKfBRDFeGjCjVjUjUjPjOjkDfFeDiBiEiKffnftJhB\
nASzDjOjVjMkNDEXkLfVkKfBRDFeGjCjVjUjUjPjOjkDfFeEiOjVjMjMffnftJhCnASjDEEXkLfVkKf\
BRDFeGjCjVjUjUjPjOjkDfFeEiUjFjYjUffnftJhDnASzFjTjPjMjJjEkOFEXkLfVkKfBRDFeGjCjVj\
UjUjPjOjkDfFeFiTjPjMjJjEffnftJhEnASzHiNjGjSjBjNjFjTkPGEXkLfVkKfBRDFeGjCjVjUjUjP\
jOjkDfFeB2kSBffnftJhFnASzIjEjSjPjQiEjPjXjOkQHEXkLfVkKfBRDFeMjEjSjPjQjEjPjXjOjMj\
JjTjUjkDfAREFdBFdCFdDFdEfffnftJhGnABXzJjTjFjMjFjDjUjJjPjOkRfVkQfHndCfJhInASzGjS\
jTjUiUjSjNkSIEXkLfVkKfBRDFeGjCjVjUjUjPjOjkDfFeDjSjTjUffnftJhLnASzIjHjSjPjVjQiUj\
XjPkTJEXkLfVjffARDFeFjHjSjPjVjQjkDfFeIjHjSjPjVjQiUjXjPffnftJhNnABXkGfVkTfJARCFe\
EjGjJjMjMFeEjGjJjMjMfnfJhOnABXkHfVkTfJndAfJhPnABXkIfVkTfJndDfJhRnABXiMfXzLjNjBj\
YjJjNjVjNiTjJjajFkUfVkTfJndZfJhTnASzEjBjEjKhSkVKEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDf\
FeDiBiEiKffnftJhUnASzEjOjVjMhSkWLEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDfFeEiOjVjMjMffnf\
tJhVnASzFjUjFjYjUhSkXMEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDfFeEiUjFjYjUffnftJhWnASzGjT\
jPjMjJjEhSkYNEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDfFeFiTjPjMjJjEffnftJhXnASzIiNjGjSjBj\
NjFjThSkZOEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDfFeB2kSBffnftJhYnASzJjEjSjPjQiEjPjXjOhS\
kaPEXkLfVkTfJRDFeMjEjSjPjQjEjPjXjOjMjJjTjUjkDfAREFdBFdCFdDFdEfffnftJhZnABXkRfVk\
afPndCfJhbnASzHjSjTjUiUjSjNhSkbQEXkLfVkTfJRDFeGjCjVjUjUjPjOjkDfFeDjSjTjUffnftJh\
enABXzIjPjOiDjIjBjOjHjFkcfVkQfHNyBnAMhebyBn0ABJhfnABjCfXkRfjkQfnf0DhNCiAnfJiBnA\
BXkcfVkafPNyBnAMiBbyBn0ABJiCnABjCfXkRfjkafnf0DhNCiDnfJiFnABXzHjPjOiDjMjJjDjLkdf\
VkMfCNyBnAMiFbyBn0ACJiHnAEjiYfRBjDfffJiInABjDfCiKnnndBnt0DhNCiJnfJiMnABXkdfVkNf\
DNyBnAMiMbyBn0ABJiNnAEjibfnf0DhNCiOnfJiQnABXkdfVkPfGNyBnAMiQbyBn0ABOiRbyiSn0ABJ\
iSnAEjPfRBFeVjQjMjFjBjTjFhAjTjFjMjFjDjUhAjBhAjMjBjZjFjSffACFXKfXhVfXMfXNfjOfnnd\
AbiVn0ADJiVnAEXhTfjOfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJiWnAEjjVfRBQhNfjBfjC\
fffJiXnAEXiXfjOfnf0DhNCiZnfJibnABXkdfVjDfENyBnAMibbyBn0ABJicnAEjjKfnf0DhNCidnfJ\
ifnABXkdfVkSfINyBnAMifbyBn0ABJjAnAEjzOjSjFjTjFjUiUjSjBjOjTjGjPjSjNkefnf0DhNCjBn\
fJjCnABXkdfVkbfQNyBnAMjCbyBn0ABJjDnAEjkefnf0DhNCjEnfJjHnABXkdfVkVfKNyBnAMjHbyBn\
0ACJjInAEjiYfRBjDfffJjJnABjDfCiKnnndBnt0DhNCjKnfJjMnABXkdfVkWfLNyBnAMjMbyBn0ABJ\
jNnAEjibfnf0DhNCjOnfJjQnABXkdfVkZfONyBnAMjQbyBn0ABOjRbyjSn0ABJjSnAEjPfRBFeVjQjM\
jFjBjTjFhAjTjFjMjFjDjUhAjBhAjMjBjZjFjSffACFXKfXhVfXMfXNfjOfnndAbjWn0ADJjWnAEXhT\
fjOfRBFePiOjFjXhAiPjOjFhAiGjSjBjNjFjSjTffJjYnAEjjVfRBQhNfjBfjCfffJjZnAEXiXfjOfn\
f0DhNCjcnfJjenABXkdfVkXfMNyBnAMjebyBn0ABJjfnAEjjKfnf0DhNCkAnfJkCnABXkdfVkOfFNyB\
nAMkCbyBn0ABJkDnAEjjHfnf0DhNCkEnfJkGnABXkdfVkYfNNyBnAMkGbyBn0ABJkHnAEjjHfnf0DhN\
CkInfACFjEfnneZjEjFjWjFjMjPjQjFjEhAjCjZhAjNjVjGjGjJjOjNjJjYhAhahTnJkMnABXzKjPjO\
iSjFjTjJjajJjOjHkffVjffABXzIjPjOiSjFjTjJjajFlAfVjffANyBnAMkMbyBn0AEJkOnABXkJfjk\
KfdChRXiLfXzEjTjJjajFlBfjjffXiMfXlBfjjffnnFeDjSjPjXFeGjDjPjMjVjNjOnfJkQnABXkJfj\
kTfdChRXiLfXlBfjjffXiMfXlBfjjffnnFeDjSjPjXFeGjDjPjMjVjNjOnfOkSbkUn0ACJkUnABXzHj\
WjJjTjJjCjMjFlCfjkTfncffJkWnABXlCfjkKfnctfAUzChGhGlDChRXiLfXlBfjjffnndZChPXiLfX\
lBfjjffXiMfXlBfjjffnnnnbkan0ACJkanABXlCfjkKfncffJkcnABXlCfjkTfnctfJlAnAEXzGjSjF\
jTjJjajFlEfXzGjMjBjZjPjVjUlFfjjffnf0DhNClCnfnfOlEblGn0ACJlGnAEXzGjDjFjOjUjFjSlG\
fVjffAnfJlInAEXzEjTjIjPjXlHfVjffAnfACQVjffAjkCfnnblMn0ACJlMnAEXlFfXlFfVjffARBFc\
tffJlOnAEXlEfXlFfVjffAnfASjD4E0AiAjf40BiAkK4B0AiAkM4C0AiAkN4D0AiAkO4F0AiAkP4G0A\
iAkQ4H0AiAkX4M0AiAkS4I0AiAkT4J0AiAkV4K0AiAkW4L0AiAkY4N0AiAkZ4O0AiAka4P0AiAkb4Q0\
AiAkA40BhABRAzIjCjVjJjMjEifiViJlIA2CCM2FCbyBn0ACJ2GCnASLAXMfXNfjOfnftO2HCb2ICn0\
ACJ2ICnAEjPfRBFegeiQjMjFjBjTjFhAjTjFjMjFjDjUhAjBjUhAjMjFjBjTjUhAhRhAjMjBjZjFjSf\
fZ2JCnAFcfACFXKfXhVfVLfAnndAb2LCn0ACJ2LCnASUBXhVfVLfAnfta2MCb2NCn0AGJ2NCnAEXhBf\
jOfRBEXgffjOfRBFehEiDjFjOjUjFjShAiBjOjDjIjPjShAiQjPjJjOjUhAjJjOhAiMjBjZjFjShAiD\
jPjOjUjFjOjUffffJ2OCnAEXgdfEXXfQhNfVUfBVhOfCRBFeIiQjPjTjJjUjJjPjOffRBARCCjNXiLf\
XMfXNfjOfnndCCjNXiMfXMfXNfjOfnndCfffJ2PCnAEXgdfEXXfQhNfVUfBVhOfCRBFeFiTjDjBjMjF\
ffRBARCFdjEFdjEfffJ2QCnAEXgdfEXXfQhNfVUfBVhOfCRBFeHiPjQjBjDjJjUjZffRBFdjEffJ2SC\
nAEXgdfEXXfQhNfVUfBVhOfCRBFeIiSjPjUjBjUjJjPjOffRBFdAffO2UCby2VCn0ABJ2VCnAEXgdfE\
XXfQhNfVUfBVhOfCRBFeMiBjVjEjJjPhAiMjFjWjFjMjTffRBARCFdAFdAfffACJEXXfQhNfVUfBVhO\
fCRBFeMiBjVjEjJjPhAiMjFjWjFjMjTffnnbnAVhOfCAXKfVUfBByBhPADhO4C0AiAL40BiAU4B0AiA\
ADAkeA2gbCBJ2gdCnAEjlIfRBVkAfAffABkA40BhAB0AhNC2gfCRBezEjUjIjJjTlJfffAEB40BiAC4\
B0AiAD4C0AiAE4D0AiAAEAhNByB");